#!/usr/bin/env python3

import sys
import os
import shutil

argc = len(sys.argv)
scripts_dir = os.environ['MRBLOG_SCRIPTS']

if argc==1:
    print('-------- Welcome to mrblog! --------')
    print('Currently configured for domain: '+os.environ['MRBLOG_DOMAIN'])
    with open(scripts_dir + '/usage', 'r') as f:
        shutil.copyfileobj(f, sys.stdout)
    print('')

elif sys.argv[1]=='new':
    os.system(scripts_dir + '/new')
elif sys.argv[1]=='publish':
    os.system(scripts_dir + '/publish')
elif sys.argv[1]=='pic':
    os.system(scripts_dir + '/post_pic ')
